In [1]:
import pandas as pd
import numpy as np

In [2]:
df_2004 = pd.read_csv('DAWN_Data_2004.csv')
df_2005 = pd.read_csv('DAWN_Data_2005.csv')
df_2006 = pd.read_csv('DAWN_Data_2006.csv')
df_2007 = pd.read_csv('DAWN_Data_2007.csv')
df_2008 = pd.read_csv('DAWN_Data_2008.csv')
df_2009 = pd.read_csv('DAWN_Data_2009.csv')
df_2010 = pd.read_csv('DAWN_Data_2010.csv')
df_2011 = pd.read_csv('DAWN_Data_2011.csv')

C:\Users\91989\AppData\Local\Temp\ipykernel_2036\2177974387.py:6: DtypeWarning: Columns (8,13,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2009 = pd.read_csv('DAWN_Data_2009.csv')


In [3]:
# To check the unique values of each column
def uniques(df):
    
    for column in df.columns:
        
        print(f'\nProcessing Column is: {column}')
        
        # printing unique values in each column to see the cleanliness of the data
        unique_vals = df[column].unique() 
        print(f'\nThe unique values in column {column} are \n{unique_vals}')
    return

def FrequencyOfValues(df):
    
    for column in df.columns:
        
        print(f'\nProcessing Column is: {column}')
        
        # printing frequency of each values in column to check how many unwanted values are there
        count_values = df[column].value_counts()
        print(f'\nThe frequency of each value in column {column} is \n{count_values}')
    return

def mapping(df):
    
    # based on the codebook changing the integer codes to their corresponding values
    
    metro_mapping = {1:'MA',2:'NY',3:'IL',4:'MI',5:'MN',6:'FL',7:'TX',8:'LA',9:'CO',10:'AZ',11:'CA-SD',12:'CA-SF',13:'WA',14:'Other'}
    agecat_mapping = {1:'<=5',2:'6-11',3:'12-17',4:'18-20',5:'21-24',6:'25-29',7:'30-34',8:'35-44',9:'45-54',10:'55-64',11:'>=65',-8:'PNS'}
    sex_mapping = {1:'M',2:'F',-8:'PNS'}
    race_mapping = {1:'white',2:'black or african american',3:'hispanic or latino',4:'all other races',-8:'PNS'}
    casetype_mapping = {1:'suicide attempt',2:'seeking detox',3:'alcohol only(age < 21)',4:'adverse reaction',5:'overmedication',6:'malicious poisoning',7:'accidental ingestion',8:'other'}
    disposition_mapping = {1:'discharged home',2:'released to police/jail',3:'reffered to detox/treatment',4:'ICU/critical care',5:'surgery',6:'chemical dependency/detox, psychiatric unit',7:'other inpatient unit',8:'transferred',9:'left against medical advice',10:'died',96:'other',-8:'PNS'}
    
    df['METRO'] = df['METRO'].replace(metro_mapping)
    df['AGECAT'] = df['AGECAT'].replace(agecat_mapping)
    df['SEX'] = df['SEX'].replace(sex_mapping)
    df['RACE'] = df['RACE'].replace(race_mapping)
    df['CASETYPE'] = df['CASETYPE'].replace(casetype_mapping)
    df['DISPOSITION'] = df['DISPOSITION'].replace(disposition_mapping)
    
    return

In [4]:
uniques(df_2004)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 168839 168840 168841]

Processing Column is: METRO

The unique values in column METRO are 
[ 4  9  6  3  7 10  2 12  5  1 14 13  8 11]

Processing Column is: STRATA

The unique values in column STRATA are 
[55 15 25 24 53 30 39 26 18  9 13 21 27 23 44 19  8 41 35 12  5 29 22  1
 10 33 37 54 36 40 45 57 46  2 14 52 56 32 49 51  7 31  3 42 20 28  6 50
 38 16 58 47 48 11 17  4 43 34]

Processing Column is: PSU

The unique values in column PSU are 
[209  50  93  90 193 112 144 100  58  30  43  67 101  76  92 168  87  77
  82  60  88  75  24 156 129  69 207  40  14 110  72   2  34  32 121 133
  31  68 197 131 150 200 154 201 103  23 171 217 204  61 176   5  49  45
 192 196 213 152 111 117 148  63 183  85   4  74  27  80 188 105  22 114
 104  59   6 158  66 167  46 107  97  78 122 175  51 108  19  65 115 184
 211 185 139 125  47  94  70 145 203 109   9 118 155 169 173 120 130 106
 163  35 214 123

In [5]:
uniques(df_2005)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 268126 268127 268128]

Processing Column is: METRO

The unique values in column METRO are 
[ 3  2  4 14 12 11  1 10 13  8  9  5  6  7]

Processing Column is: STRATA

The unique values in column STRATA are 
[53 51 35  3 12 26 25 31 49  9 33 34 32 17 37 41 19 24 54 46 28 40 10 39
 13  6 42 20  8 16 36 15  4 18 29 44 43  7  5 38 47 22 23 45  1 11 14 27
 21 48  2 50 52 30]

Processing Column is: PSU

The unique values in column PSU are 
[214 206 139   8  50 102  99 120 201 103  35 126 136 131  51 122  66 148
 162  74  98 224 185 147 119   7 106 156  42  67 154 123 109   9  55  20
 168 221  36 152 217 138  77 145  31  65 198 142 117  61  96 118  13  39
 196  70 110 202 159 153 143 173 160 167 171  28 144  33  17  69 151 187
  90  62 186  93  94 179  12   1 140  18 220  78 158 184  81 175 188  46
 189 207 137  72  23  53  71  60  54 127 107 134 129 193 203 161 100 192
  10  97  19 104 181  79 165

In [6]:
uniques(df_2006)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 269337 269338 269339]

Processing Column is: METRO

The unique values in column METRO are 
[ 1 10  3 14  2  4  5 13 11 12  8  7  9]

Processing Column is: STRATA

The unique values in column STRATA are 
[ 7  9  6  3 49 16 18 48 25  2 42 13 35 31 44 43 14 37 36 28 22 15 29 32
 26 39 21 24 19  8 34 10 47 45 20 30 12  5  4 38  1 46 41 23 33 11 27 17
 40]

Processing Column is: PSU

The unique values in column PSU are 
[ 29  40  19   7  20 204  25  73  84  23 201 115  18   3  72 181 116  57
 155 180 136 185 183  41  65 189 163 161 160 125  99 157  78 114  66 128
 142 178   5  36   9 118   8 169  95  26  30 113  87  38 151  43  28 198
  56 158 147 139 154 190 129  93  48  34  59 132  53  16  11  27 117 166
  71  22   2 197 150  94  45 168 191 127 140 152  91 187 193  37   6 175
 170 141  17  85  74  55  89  42 200  39  46 102  21  62 188   4  98 195
  24 199  75  58  32  31 156 202 153 104 119 1

In [7]:
uniques(df_2007)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 300981 300982 300983]

Processing Column is: METRO

The unique values in column METRO are 
[13  4 14  3  9  7  2  1  5 11 10 12  8]

Processing Column is: STRATA

The unique values in column STRATA are 
[32  2  1 20 34  8 15 16 29 18 43 31 44 25 22 45 26 37 33 47  4 41 42 39
 13 21 23 46 38  5 10 35 28 12  3  7 36 14 48 24 30 27 17 49 11  9  6 40
 19]

Processing Column is: PSU

The unique values in column PSU are 
[ 29  44   4  50 121  73 165 149  25  89  23  58  91 115 156  30 128   2
  35 182  85 198  41  17 204 178   6 111 136  12 141 185 152 160  84 194
 167  27   8 196  46 201 134 150  62 195 186 205  49  95  82   9  54 137
 203 118 159 122  40 142  78 119   3  69 139 154 157  36  72 102 138  32
  31  51 187 169  21  39 164 163 125 143 103 202 114 162  33 197  13 153
  70 108 158 129  71 161  34   5  43 190  86 175  74 144 193 207 206  96
  55 183  37  53  92  10  45  19  63  56  99  

In [8]:
uniques(df_2008)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 351695 351696 351697]

Processing Column is: METRO

The unique values in column METRO are 
[ 5  2 13  3 12  1  4 11  7 14  9  8 10  6]

Processing Column is: STRATA

The unique values in column STRATA are 
[26 24 38 22 45 34 33 53  2 48 27 12 28 37 52 49 42 36  3 43 17 50 16 14
 20 39 40 29 41 25 54 10  1 47 46  7 21 51 13 23 15  4 30 44 35 31 18 32
  5  9 11  6 19  8]

Processing Column is: PSU

The unique values in column PSU are 
[ 21  53  54 148  56   2 211 216 219 126 220  72  11  15  83 131  34  37
  39  28  91 183 231 147  22  87 230 104 203  12 102  76 175  58 180  95
 156  32 110 112 134 120  33 116 150  30 132  50 107  52   3 172 144  98
  88  78   4 212  23 174 223 170 158 167 109 173  82  74 113 146 194 163
  48  67 213 179  85  96 171 155 136  70 128 185 111  49 103 204 106 143
 197 133  18 125 224 228 195 214 119 141 226  47  46  69  35  14  31 135
  17 165 153 207  90 229 189

In [9]:
uniques(df_2009)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 380123 380124 380125]

Processing Column is: METRO

The unique values in column METRO are 
[14  4  1  2  8  7  9 10 12  3  5  6 13]

Processing Column is: STRATA

The unique values in column STRATA are 
[10 47 27 30 40 52  9 45 21 23 13 34 20 48 14 46  5 11 38 17 16 54  2 24
 29 51 53 26  3  1 55 19 44 32 37 43 42  7 25 28  6 39 36 22 35 50 49 41
 12  8 18  4 33 15 31]

Processing Column is: PSU

The unique values in column PSU are 
[224 188  35  27 186 133 214  98  86 205  69  72 199 143  46 118 107 172
  41  24 171 116  68 129  28  45 130  79 181  34 110  50 187 167 139 222
  13  16  38 120 109  83 162 232 138 159 161 192  74  89 180 235  54 124
  19  65  56  63 166 136 178 157 135 142  23 152   2 217  36 169  81 103
 158 164 149 226  49 234  90 117 207  15 215 202  53  70  14 220  77  10
  40 209 182  88 210 147  48 141  93  22 156  91 113 206  80 119  99  76
 236  55  21 106 176 228 114

In [10]:
FrequencyOfValues(df_2009)


Processing Column is: CASEID

The frequency of each value in column CASEID is 
1         1
253415    1
253424    1
253423    1
253422    1
         ..
126707    1
126706    1
126705    1
126704    1
380125    1
Name: CASEID, Length: 380125, dtype: int64

Processing Column is: METRO

The frequency of each value in column METRO is 
14    70057
2     58645
1     39526
4     39487
3     35241
13    28284
9     25819
5     21068
10    19808
8     12407
12    10757
6     10502
7      8524
Name: METRO, dtype: int64

Processing Column is: STRATA

The frequency of each value in column STRATA is 
38    23568
29    19025
11    17165
42    16705
32    15096
48    14273
54    13304
9     12135
44    11681
26    11546
45    10943
50    10005
19     9413
51     8967
22     8132
47     7981
40     7962
55     7938
10     7503
27     7471
46     7434
23     7418
13     7277
14     7057
28     7014
2      6691
52     6297
17     6156
3      5965
37     5912
39     5682
34     5081
35     4988
21     48

In [11]:
# dropping the row with empty values
df_2009 = df_2009.loc[df_2009['SEX'] != ' ']

In [12]:
FrequencyOfValues(df_2009)


Processing Column is: CASEID

The frequency of each value in column CASEID is 
1         1
253415    1
253424    1
253423    1
253422    1
         ..
126706    1
126705    1
126704    1
126703    1
380125    1
Name: CASEID, Length: 380124, dtype: int64

Processing Column is: METRO

The frequency of each value in column METRO is 
14    70057
2     58645
1     39525
4     39487
3     35241
13    28284
9     25819
5     21068
10    19808
8     12407
12    10757
6     10502
7      8524
Name: METRO, dtype: int64

Processing Column is: STRATA

The frequency of each value in column STRATA is 
38    23568
29    19024
11    17165
42    16705
32    15096
48    14273
54    13304
9     12135
44    11681
26    11546
45    10943
50    10005
19     9413
51     8967
22     8132
47     7981
40     7962
55     7938
10     7503
27     7471
46     7434
23     7418
13     7277
14     7057
28     7014
2      6691
52     6297
17     6156
3      5965
37     5912
39     5682
34     5081
35     4988
21     48

In [13]:
# changing the string values to integer
df_2009['SEX'] = df_2009['SEX'].astype(int)
df_2009['NUMSUBS'] = df_2009['NUMSUBS'].astype(int)
df_2009['ALCOHOL'] = df_2009['ALCOHOL'].astype(int)
df_2009['NONALCILL'] = df_2009['NONALCILL'].astype(int)
df_2009['PHARMA'] = df_2009['PHARMA'].astype(int)
df_2009['NONMEDPHARMA'] = df_2009['NONMEDPHARMA'].astype(int)
df_2009['ALLABUSE'] = df_2009['ALLABUSE'].astype(int)

In [14]:
uniques(df_2009)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 380123 380124 380125]

Processing Column is: METRO

The unique values in column METRO are 
[14  4  1  2  8  7  9 10 12  3  5  6 13]

Processing Column is: STRATA

The unique values in column STRATA are 
[10 47 27 30 40 52  9 45 21 23 13 34 20 48 14 46  5 11 38 17 16 54  2 24
 29 51 53 26  3  1 55 19 44 32 37 43 42  7 25 28  6 39 36 22 35 50 49 41
 12  8 18  4 33 15 31]

Processing Column is: PSU

The unique values in column PSU are 
[224 188  35  27 186 133 214  98  86 205  69  72 199 143  46 118 107 172
  41  24 171 116  68 129  28  45 130  79 181  34 110  50 187 167 139 222
  13  16  38 120 109  83 162 232 138 159 161 192  74  89 180 235  54 124
  19  65  56  63 166 136 178 157 135 142  23 152   2 217  36 169  81 103
 158 164 149 226  49 234  90 117 207  15 215 202  53  70  14 220  77  10
  40 209 182  88 210 147  48 141  93  22 156  91 113 206  80 119  99  76
 236  55  21 106 176 228 114

In [15]:
uniques(df_2010)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 304108 304109 304110]

Processing Column is: METRO

The unique values in column METRO are 
[ 4 10  8  2  3  7  5  9  1 13 14 12 11  6]

Processing Column is: STRATA

The unique values in column STRATA are 
[24 16 13 22 12 43  6 31 47 11 26 15 36 20 45 18 25 38  3 39 30 10 42  2
 41 34 35  1 17 48 33 21  7 37 19  9  8 14 32 23 28 29 44 40  4 46 27  5]

Processing Column is: PSU

The unique values in column PSU are 
[109  68  52 101  50 210  23 142 113 206 233  45 120  64 169 207  91 215
 217 170  77 118 119  49 173 183 121 112 205   9 232 188 177 137  41 176
 203   6 196 154  11 158   1  62  71  40 237   7 151 185 166  99  26 198
 114 155 182  69  81 149  97 208  32  19  61  90  29  84  60 222 186  85
  87 202 153 175 231 102  21 194  33 146 145 147 221 218  25 230  96 156
 106  47  53  94  46 127  28 184  63  20 110 133 157 115 162 116 213  43
 223  27 171  57  92 103 160 190 195  13  51 16

In [16]:
uniques(df_2011)


Processing Column is: CASEID

The unique values in column CASEID are 
[     1      2      3 ... 229209 229210 229211]

Processing Column is: METRO

The unique values in column METRO are 
[ 2  7 10  1 14  6 12  4 13  5  3  8  9 11]

Processing Column is: STRATA

The unique values in column STRATA are 
[25 29  7  8 22 10  3 51 46 13 32 50 41 40  9 14 20 37 33 26 11 19 28 35
 38 21 24 43 48 30 23 12 36 15  2 17 45 34 31  4 42  6 27  5 39 18  1 49
 44 16 47]

Processing Column is: PSU

The unique values in column PSU are 
[108 129  25  29  94  40   6 232   5 210  24  48 145 227 192 188  97  96
  36  58 109  87  98  59 172 148  27 115 184  43  79 126  85 114 165 176
  51  91 103  80  54 197 190  84 187 219 140 100   8  86 112   7 110  82
  47 166 116 152  64 225 170  30 200 175 137 118  28 185  34  60  37   4
  26  70 107 136 134 208 202 189 161 141  93 150   9 147 194  44  20  31
 162 196 163 182 146  52 120  14  19   3 149 179  99 159 181  72 101 128
   1  49 186 113 119 215  41  92  95 

In [17]:
mapping(df_2004)
mapping(df_2005)
mapping(df_2006)
mapping(df_2007)
mapping(df_2008)
mapping(df_2009)
mapping(df_2010)
mapping(df_2011)

In [18]:
df_2004

CASEID  METRO  STRATA  PSU  REPLICATE     CASEWGT  PSUFRAME AGECAT  \
0            1     MI      55  209          1    1.305268        19  21-24   
1            2     CO      15   50          2    1.017082         2  12-17   
2            3     FL      25   93          2    1.595423         5  25-29   
3            4     IL      24   90          2    3.697978        25  21-24   
4            5     TX      53  193          1    2.859101        22  45-54   
...        ...    ...     ...  ...        ...         ...       ...    ...   
168836  168837     MI      33  124          2    3.136721         9  18-20   
168837  168838     MN      23   81          2    3.486044        19    <=5   
168838  168839     MN      21   70          1    6.697147         8  12-17   
168839  168840  Other      32  118          2  215.800313       447   >=65   
168840  168841     CO      20   66          1    1.103569         3  25-29   

       SEX                       RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0        M                      white  ...        3        4        1   
1        F                        PNS  ...        2        1        1   
2        M  black or african american  ...        2        3        2   
3        M         hispanic or latino  ...        4        2        2   
4        M                      white  ...        1        3        1   
...     ..                        ...  ...      ...      ...      ...   
168836   F                        PNS  ...        4        4        1   
168837   F                      white  ...        2        2        1   
168838   F                      white  ...        4        4        1   
168839   F                      white  ...        2        2        1   
168840   M                        PNS  ...        4        2        2   

                      CASETYPE                                  DISPOSITION  \
0              suicide attempt  chemical dependency/detox, psychiatric unit   
1                        other                              discharged home   
2                        other                              discharged home   
3                        other                              discharged home   
4                        other                              discharged home   
...                        ...                                          ...   
168836                   other                              discharged home   
168837        adverse reaction                              discharged home   
168838  alcohol only(age < 21)                              discharged home   
168839        adverse reaction                              discharged home   
168840                   other                              discharged home   

       ALCOHOL  NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0            0          0       1             0         0  
1            0          1       0             0         1  
2            1          1       0             0         1  
3            1          1       0             0         1  
4            0          0       1             1         1  
...        ...        ...     ...           ...       ...  
168836       0          1       0             0         1  
168837       0          0       1             0         0  
168838       1          0       0             0         1  
168839       0          0       1             0         0  
168840       1          0       1             1         1  

[168841 rows x 21 columns]

In [19]:
df_2005

CASEID  METRO  STRATA  PSU  REPLICATE     CASEWGT  PSUFRAME AGECAT  \
0            1     IL      53  214          1    4.004894        26  25-29   
1            2     NY      51  206          1    2.186800         7  35-44   
2            3     MI      35  139          1    2.928572         9  35-44   
3            4     NY       3    8          1    2.307630         9  35-44   
4            5  Other      12   50          2  101.000540       736  55-64   
...        ...    ...     ...  ...        ...         ...       ...    ...   
268123  268124     CO      36  142          1    1.159632         3    <=5   
268124  268125  Other      31  120          1    2.399979        13  35-44   
268125  268126     FL       5   18          2    1.653076        15  25-29   
268126  268127     NY       3    9          2    2.543016         9  45-54   
268127  268128     AZ      28  107          1    0.926901         7  18-20   

       SEX                       RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0        F                      white  ...        4        4        2   
1        F  black or african american  ...        4        2        2   
2        F                        PNS  ...        1        2        1   
3        F                        PNS  ...        2        4        1   
4        F                      white  ...        1        2        1   
...     ..                        ...  ...      ...      ...      ...   
268123   M                      white  ...        2        3        2   
268124   M                      white  ...        3        4        2   
268125   M                        PNS  ...        1        3        1   
268126   M  black or african american  ...        2        3        1   
268127   F         hispanic or latino  ...        1        1        1   

                      CASETYPE           DISPOSITION ALCOHOL  NONALCILL  \
0                        other       discharged home       0          1   
1                seeking detox       discharged home       1          1   
2             adverse reaction       discharged home       0          0   
3             adverse reaction       discharged home       0          0   
4             adverse reaction       discharged home       0          0   
...                        ...                   ...     ...        ...   
268123        adverse reaction                 other       0          0   
268124         suicide attempt       discharged home       1          0   
268125                   other       discharged home       0          1   
268126                   other  other inpatient unit       0          1   
268127  alcohol only(age < 21)       discharged home       1          0   

        PHARMA  NONMEDPHARMA  ALLABUSE  
0            1             1         1  
1            0             0         1  
2            1             0         0  
3            1             0         0  
4            1             0         0  
...        ...           ...       ...  
268123       1             0         0  
268124       1             0         1  
268125       0             0         1  
268126       0             0         1  
268127       0             0         1  

[268128 rows x 21 columns]

In [20]:
df_2006

CASEID  METRO  STRATA  PSU  REPLICATE     CASEWGT  PSUFRAME AGECAT  \
0            1     MA       7   29          1    1.531256        20  35-44   
1            2     AZ       9   40          1    4.976994         7  30-34   
2            3     IL       6   19          2    2.972395        26   >=65   
3            4     AZ       3    7          2    1.858320         6  35-44   
4            5     IL       6   20          1    1.706800        26  45-54   
...        ...    ...     ...  ...        ...         ...       ...    ...   
269334  269335     MA      44  187          1    2.109792        10  35-44   
269335  269336     LA      28  125          1    0.846286        22  35-44   
269336  269337  Other      42  180          2  104.836321       754  12-17   
269337  269338     IL       6   26          1    2.699768        26    <=5   
269338  269339     TX      15   67          2    8.497812        15  18-20   

       SEX                       RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0        F                      white  ...        2        4        5   
1        M         hispanic or latino  ...        3        3        1   
2        M                        PNS  ...        3        2        1   
3        F                      white  ...        2        3        2   
4        M         hispanic or latino  ...        3        4        1   
...     ..                        ...  ...      ...      ...      ...   
269334   F                      white  ...        1        1        2   
269335   F  black or african american  ...        3        2        3   
269336   M                      white  ...        2        3        1   
269337   F  black or african american  ...        3        4        1   
269338   M         hispanic or latino  ...        2        4        1   

                    CASETYPE                                  DISPOSITION  \
0              seeking detox  chemical dependency/detox, psychiatric unit   
1                      other                         other inpatient unit   
2           adverse reaction                         other inpatient unit   
3              seeking detox                                  transferred   
4           adverse reaction                  left against medical advice   
...                      ...                                          ...   
269334      adverse reaction                              discharged home   
269335                 other                              discharged home   
269336                 other                              discharged home   
269337  accidental ingestion                              discharged home   
269338        overmedication                                  transferred   

       ALCOHOL  NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0            1          1       1             0         1  
1            0          1       0             0         1  
2            0          0       1             0         0  
3            1          1       0             0         1  
4            0          0       1             0         0  
...        ...        ...     ...           ...       ...  
269334       0          0       1             0         0  
269335       0          1       1             1         1  
269336       0          1       0             0         1  
269337       0          0       1             0         0  
269338       0          0       1             1         1  

[269339 rows x 21 columns]

In [21]:
df_2007

CASEID  METRO  STRATA  PSU  REPLICATE     CASEWGT  PSUFRAME AGECAT  \
0            1     WA      32   29          2    5.830726        11  25-29   
1            2     MI       2   44          1    3.303042         9  55-64   
2            3  Other       1    4          1   33.562551       220  45-54   
3            4     IL      20   50          2    4.622412        25   >=65   
4            5  Other      34  121          1  165.547692       452  21-24   
...        ...    ...     ...  ...        ...         ...       ...    ...   
300978  300979  Other      27  124          2  136.387360       385  55-64   
300979  300980     NY      39  185          2    2.755892         9  30-34   
300980  300981     IL      41   45          2    2.708563        26  18-20   
300981  300982     CO      13   78          1    1.233453         3  12-17   
300982  300983     MI       2  203          2    2.793884         9  35-44   

       SEX                       RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0        M         hispanic or latino  ...        1        2        1   
1        M  black or african american  ...        2        2        1   
2        F                      white  ...        4        1        1   
3        M                      white  ...        2        3        1   
4        M  black or african american  ...        2        1        1   
...     ..                        ...  ...      ...      ...      ...   
300978   M                      white  ...        1        2        1   
300979   F                        PNS  ...        4        2        1   
300980   M                        PNS  ...        1        4        3   
300981   F                        PNS  ...        4        4        1   
300982   F                      white  ...        4        3        1   

                CASETYPE                                  DISPOSITION ALCOHOL  \
0       adverse reaction                              discharged home       0   
1                  other                              discharged home       0   
2        suicide attempt  chemical dependency/detox, psychiatric unit       0   
3       adverse reaction                              discharged home       0   
4                  other                      released to police/jail       0   
...                  ...                                          ...     ...   
300978  adverse reaction                              discharged home       0   
300979  adverse reaction                              discharged home       0   
300980     seeking detox                         other inpatient unit       1   
300981             other                                  transferred       0   
300982  adverse reaction                              discharged home       0   

        NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0               0       1             0         0  
1               1       0             0         1  
2               0       1             0         0  
3               0       1             0         0  
4               1       0             0         1  
...           ...     ...           ...       ...  
300978          0       1             0         0  
300979          0       1             0         0  
300980          1       0             0         1  
300981          0       1             1         1  
300982          0       1             0         0  

[300983 rows x 21 columns]

In [22]:
df_2008

CASEID METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT SEX  \
0            1    MN      26   21          1  5.373432        12   >=65   F   
1            2    NY      24   53          1  1.128572         7  35-44   F   
2            3    WA      38   54          1  1.786770         8  21-24   M   
3            4    IL      22  148          2  1.329842        26  25-29   F   
4            5    NY      45   56          1  2.933942        17  30-34   F   
...        ...   ...     ...  ...        ...       ...       ...    ...  ..   
351692  351693    MI       2  118          1  1.396474        18   >=65   M   
351693  351694    MI      23  186          2  2.614033         8  45-54   M   
351694  351695    NY      53   88          1  2.535531         9  18-20   F   
351695  351696    IL      25   59          1  3.368428        18    <=5   F   
351696  351697    NY      53   78          1  2.444156         9  21-24   F   

                             RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0       black or african american  ...        1        2        1   
1                 all other races  ...        4        1        1   
2       black or african american  ...        2        2        1   
3       black or african american  ...        1        3        2   
4                             PNS  ...        4        3        2   
...                           ...  ...      ...      ...      ...   
351692                      white  ...        1        1        1   
351693                      white  ...        1        3        2   
351694                        PNS  ...        1        4        1   
351695         hispanic or latino  ...        1        2        4   
351696                      white  ...        1        4        1   

                CASETYPE           DISPOSITION ALCOHOL  NONALCILL  PHARMA  \
0       adverse reaction  other inpatient unit       0          0       1   
1       adverse reaction       discharged home       0          0       1   
2                  other       discharged home       0          1       0   
3                  other       discharged home       1          1       0   
4       adverse reaction  other inpatient unit       0          0       1   
...                  ...                   ...     ...        ...     ...   
351692  adverse reaction       discharged home       0          0       1   
351693             other       discharged home       0          0       1   
351694    overmedication       discharged home       0          0       1   
351695             other       discharged home       0          0       1   
351696  adverse reaction       discharged home       0          0       1   

        NONMEDPHARMA  ALLABUSE  
0                  0         0  
1                  0         0  
2                  0         1  
3                  0         1  
4                  0         0  
...              ...       ...  
351692             0         0  
351693             1         1  
351694             1         1  
351695             1         1  
351696             0         0  

[351697 rows x 21 columns]

In [23]:
df_2009

CASEID  METRO  STRATA  PSU  REPLICATE    CASEWGT  PSUFRAME AGECAT SEX  \
0            1  Other      10  224          1  58.941201      1203  25-29   F   
1            2     MI      47  188          1   1.383026        19  35-44   M   
2            3     MA      27   35          1   4.500811        10  18-20   M   
3            4  Other      30   27          1   5.161360         5    <=5   F   
4            5     NY      40  186          2   0.972520         3  30-34   M   
...        ...    ...     ...  ...        ...        ...       ...    ...  ..   
380120  380121     MI      38  168          1   1.841809         9   >=65   F   
380121  380122     MA      44  204          2   1.718199        10  18-20   M   
380122  380123     MA      27   35          1   2.022822        10  35-44   M   
380123  380124     AZ      16  166          1   3.953762        16    <=5   M   
380124  380125  Other      20  143          1   3.952220        12   6-11   M   

                             RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0                           white  ...        3        4        2   
1       black or african american  ...        2        3        1   
2                           white  ...        1        1        1   
3                             PNS  ...        1        4        1   
4       black or african american  ...        1        2        1   
...                           ...  ...      ...      ...      ...   
380120                        PNS  ...        4        3        1   
380121                      white  ...        2        1        1   
380122                      white  ...        3        3        2   
380123                      white  ...        3        2        1   
380124                      white  ...        2        3        1   

                      CASETYPE                  DISPOSITION ALCOHOL  \
0             adverse reaction              discharged home       0   
1                        other  reffered to detox/treatment       0   
2       alcohol only(age < 21)              discharged home       1   
3               overmedication              discharged home       0   
4                        other              discharged home       0   
...                        ...                          ...     ...   
380120        adverse reaction         other inpatient unit       0   
380121  alcohol only(age < 21)              discharged home       1   
380122           seeking detox                  transferred       0   
380123        adverse reaction              discharged home       0   
380124        adverse reaction              discharged home       0   

        NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0               0       1             0         0  
1               1       0             0         1  
2               0       0             0         1  
3               0       1             1         1  
4               1       0             0         1  
...           ...     ...           ...       ...  
380120          0       1             0         0  
380121          0       0             0         1  
380122          1       0             0         1  
380123          0       1             0         0  
380124          0       1             0         0  

[380124 rows x 21 columns]

In [24]:
df_2010

CASEID  METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT SEX  \
0            1     MI      24  109          2  2.561115         9  25-29   M   
1            2     AZ      16   68          2  2.549471         8   >=65   F   
2            3     LA      13   52          2  6.540357         9  21-24   M   
3            4     NY      22  101          2  2.467445         9  45-54   F   
4            5     NY      12   50          2  1.038926         3    <=5   F   
...        ...    ...     ...  ...        ...       ...       ...    ...  ..   
304105  304106     MI      24  112          1  2.510959         9  45-54   F   
304106  304107     FL      14   59          1  1.833118         3  35-44   F   
304107  304108     LA      44  213          2  3.699503        28  55-64   F   
304108  304109  CA-SF       2    6          2  1.546528         2  12-17   M   
304109  304110     NY      15   61          1  3.616160         8  55-64   M   

                             RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0                           white  ...        1        1        2   
1              hispanic or latino  ...        1        3        1   
2       black or african american  ...        3        3        1   
3              hispanic or latino  ...        1        4        2   
4       black or african american  ...        4        1        1   
...                           ...  ...      ...      ...      ...   
304105  black or african american  ...        2        3        1   
304106  black or african american  ...        3        3        2   
304107                      white  ...        4        2        1   
304108         hispanic or latino  ...        4        2        2   
304109         hispanic or latino  ...        4        3        3   

                CASETYPE                                  DISPOSITION ALCOHOL  \
0         overmedication  chemical dependency/detox, psychiatric unit       1   
1       adverse reaction                         other inpatient unit       0   
2                  other                      released to police/jail       0   
3                  other  chemical dependency/detox, psychiatric unit       0   
4       adverse reaction                              discharged home       0   
...                  ...                                          ...     ...   
304105   suicide attempt                                  transferred       0   
304106             other                         other inpatient unit       0   
304107  adverse reaction                              discharged home       0   
304108             other                              discharged home       1   
304109             other                              discharged home       1   

        NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0               0       1             1         1  
1               0       1             0         0  
2               0       1             1         1  
3               1       0             0         1  
4               0       1             0         0  
...           ...     ...           ...       ...  
304105          0       1             0         0  
304106          0       1             1         1  
304107          0       1             0         0  
304108          1       0             0         1  
304109          0       1             1         1  

[304110 rows x 21 columns]

In [25]:
df_2011

CASEID METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT SEX  \
0            1    NY      25  108          2  0.942635         3  18-20   M   
1            2    NY      29  129          2  5.992011         9   >=65   M   
2            3    TX       7   25          1  4.723172         6   >=65   F   
3            4    AZ       8   29          2  4.080147         6   6-11   M   
4            5    MA      22   94          2  5.177709        10  25-29   M   
...        ...   ...     ...  ...        ...       ...       ...    ...  ..   
229206  229207    MN      20   85          2  4.203385         8   >=65   F   
229207  229208    WA      26  111          2  4.215246        11  45-54   F   
229208  229209    MN      20   87          1  4.139613         8  35-44   F   
229209  229210    IL      30  132          2  1.601442        26    <=5   F   
229210  229211    MI      48  214          1  5.261895        17  55-64   F   

                             RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0       black or african american  ...        4        1        2   
1              hispanic or latino  ...        3        4        1   
2       black or african american  ...        4        3        1   
3              hispanic or latino  ...        2        2        1   
4              hispanic or latino  ...        3        4        3   
...                           ...  ...      ...      ...      ...   
229206                      white  ...        3        4        1   
229207                      white  ...        3        3        1   
229208                        PNS  ...        3        4        1   
229209  black or african american  ...        2        2        1   
229210  black or african american  ...        1        1        1   

                CASETYPE                                  DISPOSITION ALCOHOL  \
0                  other  chemical dependency/detox, psychiatric unit       1   
1       adverse reaction                         other inpatient unit       0   
2       adverse reaction                              discharged home       0   
3       adverse reaction                         other inpatient unit       0   
4                  other                                  transferred       1   
...                  ...                                          ...     ...   
229206  adverse reaction                              discharged home       0   
229207             other                              discharged home       0   
229208  adverse reaction                              discharged home       0   
229209  adverse reaction                              discharged home       0   
229210  adverse reaction                            ICU/critical care       0   

        NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0               1       0             0         1  
1               0       1             0         0  
2               0       1             0         0  
3               0       1             0         0  
4               1       0             0         1  
...           ...     ...           ...       ...  
229206          0       1             0         0  
229207          0       1             1         1  
229208          0       1             0         0  
229209          0       1             0         0  
229210          0       1             0         0  

[229211 rows x 21 columns]

In [26]:
# creating a combined data of all years
df_2004_2011 = pd.concat([df_2004, df_2005, df_2006, df_2007, df_2008, df_2009, df_2010, df_2011], axis=0)

In [27]:
df_2004_2011['YEAR'].unique()

array([2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011], dtype=int64)

In [29]:
df_2004_2011

CASEID METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT SEX  \
0            1    MI      55  209          1  1.305268        19  21-24   M   
1            2    CO      15   50          2  1.017082         2  12-17   F   
2            3    FL      25   93          2  1.595423         5  25-29   M   
3            4    IL      24   90          2  3.697978        25  21-24   M   
4            5    TX      53  193          1  2.859101        22  45-54   M   
...        ...   ...     ...  ...        ...       ...       ...    ...  ..   
229206  229207    MN      20   85          2  4.203385         8   >=65   F   
229207  229208    WA      26  111          2  4.215246        11  45-54   F   
229208  229209    MN      20   87          1  4.139613         8  35-44   F   
229209  229210    IL      30  132          2  1.601442        26    <=5   F   
229210  229211    MI      48  214          1  5.261895        17  55-64   F   

                             RACE  ...  QUARTER  DAYPART  NUMSUBS  \
0                           white  ...        3        4        1   
1                             PNS  ...        2        1        1   
2       black or african american  ...        2        3        2   
3              hispanic or latino  ...        4        2        2   
4                           white  ...        1        3        1   
...                           ...  ...      ...      ...      ...   
229206                      white  ...        3        4        1   
229207                      white  ...        3        3        1   
229208                        PNS  ...        3        4        1   
229209  black or african american  ...        2        2        1   
229210  black or african american  ...        1        1        1   

                CASETYPE                                  DISPOSITION ALCOHOL  \
0        suicide attempt  chemical dependency/detox, psychiatric unit       0   
1                  other                              discharged home       0   
2                  other                              discharged home       1   
3                  other                              discharged home       1   
4                  other                              discharged home       0   
...                  ...                                          ...     ...   
229206  adverse reaction                              discharged home       0   
229207             other                              discharged home       0   
229208  adverse reaction                              discharged home       0   
229209  adverse reaction                              discharged home       0   
229210  adverse reaction                            ICU/critical care       0   

        NONALCILL  PHARMA  NONMEDPHARMA  ALLABUSE  
0               0       1             0         0  
1               1       0             0         1  
2               1       0             0         1  
3               1       0             0         1  
4               0       1             1         1  
...           ...     ...           ...       ...  
229206          0       1             0         0  
229207          0       1             1         1  
229208          0       1             0         0  
229209          0       1             0         0  
229210          0       1             0         0  

[2272433 rows x 21 columns]